name: JMeter

on:
  push:
    branches:
      - master
      - release

jobs:
  action_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Lint all YAML files in the directory
      #   uses: ibiqlik/action-yamllint@master

      - name: Run JMeter Action 1 C4Life
        uses: ./
        with:
          testFilePath: C4Life.jmx
          outputReportsFolder: reports/c4life/
          args: "--loglevel INFO"

      # - name: Run JMeter Action 2 Intaller App
      #   uses: ./
      #   with:
      #     testFilePath: Installer.jmx
      #     outputReportsFolder: reports/intaller/
      #     args: "--loglevel INFO"

      # - name: Run JMeter Action 3 Device Management
      #   uses: ./
      #   with:
      #     testFilePath: DM.jmx
      #     outputReportsFolder: reports/device_management/
      #     args: "--loglevel INFO"

      # - name: Run JMeter Action 4 Titan
      #   uses: ./
      #   with:
      #     testFilePath: Titan.jmx
      #     outputReportsFolder: reports/titan/
      #     args: "--loglevel INFO"

      - name: Reporting C4life
        uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results-c4life
          path: reports/c4life/

      # - name: Reporting Installer
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: jmeter-test-results-installer
      #     path: reports/intaller/

      # - name: Reporting Device Management
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: jmeter-test-results-device-management
      #     path: reports/device_management/

      # - name: Titan Installer
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: jmeter-test-results-titan
      #     path: reports/titan/
